name: multiparingbase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  permission_handler: 10.2.0
  flutter_bluetooth_serial: 0.4.0
  fl_chart: 0.55.2
  hive: 2.2.3
  csv: 5.0.1
  intl: 0.17.0
  file_saver: 0.1.1
  isar: 3.0.4
  isar_flutter_libs: 3.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.0.4

flutter: 
  uses-material-design: true

